# Generated by Django 5.2.3 on 2026-04-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='recipient_phones',
            field=models.JSONField(default=list, help_text='Stored list of phone numbers selected at campaign creation time.'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='trigger_event',
            field=models.CharField(blank=True, choices=[('order_created_pickup_paid', 'Order Created (Pickup · Paid)'), ('order_created_pickup_deposit', 'Order Created (Pickup · Deposit)'), ('order_created_pickup_unpaid', 'Order Created (Pickup · Unpaid)'), ('order_created_delivery_paid', 'Order Created (Delivery · Paid)'), ('order_created_delivery_deposit', 'Order Created (Delivery · Deposit)'), ('order_created_delivery_unpaid', 'Order Created (Delivery · Unpaid)'), ('order_ready_pickup', 'Order Ready (Pickup)'), ('order_ready_delivery', 'Order Ready (Delivery)'), ('order_dispatched', 'Order Dispatched'), ('order_delivered', 'Order Delivered'), ('payment_received', 'Payment Received'), ('payment_reminder', 'Payment Reminder'), ('payment_overdue', 'Payment Overdue')], max_length=40),
        ),
    ]
