# Generated by Django 6.0.3 on 2026-04-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_sale_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('baker', 'With Baker'), ('quality', 'Quality Check'), ('decorator', 'With Decorator'), ('ready', 'Ready'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], db_index=True, default='pending', max_length=20),
        ),
    ]
