# Generated by Django 6.0.3 on 2026-04-03 20:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_dailybatchitem_menu_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('direction', models.CharField(choices=[('in', 'Revenue'), ('out', 'Expense')], db_index=True, max_length=3)),
                ('type', models.CharField(choices=[('order_payment', 'Order Payment'), ('sale', 'Walk-in Sale'), ('stock_expense', 'Stock Expense'), ('business_expense', 'Business Expense')], db_index=True, max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('card', 'Card'), ('cheque', 'Cheque')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('paid_to', models.CharField(blank=True, max_length=200)),
                ('receipt_ref', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_period', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.sale')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['direction', 'date'], name='finance_fin_directi_279cb2_idx'), models.Index(fields=['type', 'date'], name='finance_fin_type_37a021_idx')],
            },
        ),
    ]
